version: "3.9"

services:
  db-docuhub-morning:
    image: postgres:17.5-bullseye
    container_name: db-docuhub-morning
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer
    ports:
      - "5400:5432"
    volumes:
      - postgres_morning_vol:/var/lib/postgresql/data
    networks:
      - docuhub_morning_net

  kc-docuhub-morning:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: kc-docuhub-morning
    depends_on:
      db-docuhub-morning:
        condition: service_started
    environment:
      # Database Configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db-docuhub-morning:5432/db_keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: qwer

      # Admin User
      KC_BOOTSTRAP_ADMIN_USERNAME: kcadmin
      KC_BOOTSTRAP_ADMIN_PASSWORD: qwer

      # Hostname & Proxy (HTTP only, proxy handles HTTPS)
      KC_HOSTNAME: http://keycloak.docuhub.me
      KC_PROXY: edge
      KC_PROXY_HEADERS: "true"  # read X-Forwarded-* headers from reverse proxy
      KC_HTTP_ENABLED: "true"   # Keycloak runs in HTTP mode
    ports:
      - "9090:8080"  # host port 9090 → container port 8080
    volumes:
      - ./keycloak/themes:/opt/keycloak/providers/
      - ./keycloak/conf:/opt/keycloak/conf
      - ./keycloak/data:/opt/keycloak/data
      - ./keycloak/data/tmp:/opt/keycloak/data/tmp
    networks:
      - docuhub_morning_net
    command: start

  minio-docuhub-morning:
    image: quay.io/minio/minio
    container_name: minio-docuhub-morning
    environment:
      MINIO_ROOT_USER: minadmin
      MINIO_ROOT_PASSWORD: qwer1234
      MINIO_BROWSER_REDIRECT_URL: https://minio.docuhub.me/
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console UI
    volumes:
      - minio_morning_vol:/data
    networks:
      - docuhub_morning_net
    command: server /data --console-address ":9001"
# build 
volumes:
  postgres_morning_vol:
  minio_morning_vol:

networks:
  docuhub_morning_net:
